### ISSUE TITLE
github regex is still too broad

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/go-neb#234] opened 2018-06-11 09:51 UTC
https://github.com/matrix-org/matrix-appservice-irc#4-running triggers matrix-org/matrix-appservice-irc#4

**Comment by Kegsay** [comment] 2020-02-13 11:57
Dupe of https://github.com/matrix-org/go-neb/issues/186 - albeit for URLs not code blocks

**Closed by Kegsay** 2020-02-13 11:57 UTC
