### ISSUE TITLE
Github: bot does not report updates if repo is transferred

### ISSUE THREAD

**Issue by cmcaine** [matrix-org/go-neb#245] opened 2018-09-03 12:36 UTC
More info, some of it possibly riot-web related: https://github.com/vector-im/riot-web/issues/7266

Steps to reproduce:

- make a github repo
- add github integration bot using riot-web
- transfer repo to an organisation you own

I expected the integration to continue despite the transfer and for the bot to continue to notify the channel about issues, commits, etc.

**Comment by turt2live** [comment] 2018-09-03 14:37
Duplicate of https://github.com/matrix-org/go-neb/issues/141

**Closed by turt2live** 2018-09-03 14:37 UTC
