### ISSUE TITLE
RSS: https://apod.nasa.gov/apod.rss doesn't work.

### ISSUE THREAD

**Issue by aliencq** [matrix-org/go-neb#90] opened 2016-10-15 14:34 UTC
It's over 24h already since it was added via integration UI, but still nothing.

**Comment by Kegsay** [comment] 2016-10-18 13:21
https://github.com/matrix-org/go-neb/commit/299164d525d860dc80c2cd0e5dba26e77497f86d - Will add a tracker myself and close this when I can confirm that this feed is now working. Thanks for your patience :)

**Comment by aliencq** [comment] 2016-10-18 18:46
Thank you, waiting for a new post :)

**Comment by aliencq** [comment] 2016-10-19 07:49
It works now.

**Comment by Kegsay** [comment] 2016-10-19 08:12
Works for me too \o/ Pretty!

**Closed by Kegsay** 2016-10-19 08:12 UTC
Labels: bug, integ:rss
