### ISSUE TITLE
github expansion too greedy

### ISSUE THREAD

**Issue by t3chguy** [matrix-org/go-neb#200] opened 2017-08-29 07:34 UTC
![](https://riot.ovh/_matrix/media/v1/download/riot.ovh/OChyOJZxLtfKTvpukkPIgFuN)

**Comment by turt2live** [comment] 2017-12-22 17:46
related/duplicate of https://github.com/matrix-org/go-neb/issues/170

**Closed** 2017-12-22 17:54 UTC
