### ISSUE TITLE
GitHub: allow ignoring branches

### ISSUE THREAD

**Issue by TheLastProject** [matrix-org/go-neb#228] opened 2018-04-22 19:52 UTC
At Pext/Pext, we use @PextBot to push Linux AppImages and macOS .dmg files to the continuous tag and put it on releases. go-neb also announces these events, making things... rather spammy by making every commit show up twice:https://matrix.to/#/!PpGTFZHyuicvPDeMUH:matrix.org/$15244240065192691qRJVE:matrix.org

It would be great if I could ignore the tags/branches to stop this spam.

**Comment by t3chguy** [comment] 2018-04-22 20:02
Duplicate of #185

**Closed** 2018-04-22 20:03 UTC
