### ISSUE TITLE
GitHub: "New issues" shouldn't report on issues edit and closing

### ISSUE THREAD

**Issue by Croydon** [matrix-org/go-neb#257] opened 2018-12-04 07:33 UTC
There should be more filtering options so one and choose to gets reports for issues editing and closing as well, but "New issues" shouldn't contain these events.

**Comment by turt2live** [comment] 2018-12-04 07:52
Duplicate of https://github.com/matrix-org/go-neb/issues/191

**Closed by turt2live** 2018-12-04 07:52 UTC
