### ISSUE TITLE
Support for Riot's Encryption?

### ISSUE THREAD

**Issue by cathalgarvey** [matrix-org/go-neb#220] opened 2018-02-26 12:46 UTC
Hi folks, either chalk this up as a feature-request or a wontfix, but I'm just wondering.

Riot uses a ratchet-based cryptosystem for multi-user rooms. I believe Bots can join those rooms and make posts, but won't be able to understand the messages there without access to the session keys.

Is there a way to provide crypto integration for bots using go-neb, or any other Matrix bot framework, right now?

**Comment by uhoreg** [comment] 2018-02-26 14:05
This is a duplicate of #157.

**Comment by cathalgarvey** [comment] 2018-02-26 14:29
Sorry! I searched but "crypto" didn't seem to turn anything up for me. Will read there.

On 26 February 2018 14:05:36 GMT+00:00, Hubert Chathi <notifications@github.com> wrote:
>This is a duplicate of #157.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/matrix-org/go-neb/issues/220#issuecomment-368513794

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Closed** 2018-02-26 20:00 UTC

**Comment by t3chguy** [comment] 2018-02-26 20:01
> Any other Matrix bot framework

Yes @cathalgarvey
https://gitlab.com/argit/hello-matrix-bot
